/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datos;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import conex.conexion;
import static datos.FrmDatosRegistro.tblClientes;
import java.sql.Connection;

/**
 *
 * @author Admin
 */
public class FrmDatosProducto extends javax.swing.JFrame {

    conexion cc = new conexion();
    Connection con = cc.conexion();
    /**
     * Creates new form FrmDatosProducto
     */
    public FrmDatosProducto() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_detallesAlmacen = new javax.swing.JButton();
        btn_irAGestion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Productos de Almacén");

        btn_detallesAlmacen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_detallesAlmacen.setText("Nuevo");
        btn_detallesAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detallesAlmacenActionPerformed(evt);
            }
        });

        btn_irAGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/íconos/Go-back_36760.png"))); // NOI18N
        btn_irAGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_irAGestionActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_detallesAlmacen)
                        .addGap(78, 78, 78)
                        .addComponent(btn_irAGestion))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_detallesAlmacen)
                    .addComponent(btn_irAGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_detallesAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detallesAlmacenActionPerformed
        irADAlmacen();
    }//GEN-LAST:event_btn_detallesAlmacenActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        enviarDatosVentana();
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btn_irAGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_irAGestionActionPerformed
        irAGestion();
    }//GEN-LAST:event_btn_irAGestionActionPerformed
    
    public void irAGestion(){
        this.setVisible(false);
        Frmgestion gestion = new Frmgestion();
        gestion.setVisible(true);
    }
    
    public void enviarDatosVentana(){
        if (tblProductos.getSelectedRow()>=0) {
        FrmActualizarProducto abrir = new FrmActualizarProducto();
        abrir.setVisible(true);
            try {
                DefaultTableModel tm = (DefaultTableModel)tblProductos.getModel();
                
                int ID1 = Integer.parseInt(String.valueOf(tm.getValueAt(tblProductos.getSelectedRow(),0)));
                String nombreProducto = String.valueOf(tm.getValueAt(tblProductos.getSelectedRow(), 1));
                String marca = String.valueOf(tm.getValueAt(tblProductos.getSelectedRow(), 2));
                String categoria = String.valueOf(tm.getValueAt(tblProductos.getSelectedRow(), 3));
                String precio = String.valueOf(tm.getValueAt(tblProductos.getSelectedRow(), 4));
                String stock = String.valueOf(tm.getValueAt(tblProductos.getSelectedRow(), 5));
                
                FrmActualizarProducto.txt_nombreProducto.setText(nombreProducto);
                FrmActualizarProducto.txt_marcaProducto.setText(marca);
                FrmActualizarProducto.txt_categoriaProducto.setText(categoria);
                FrmActualizarProducto.txt_precio.setText(precio);
                FrmActualizarProducto.txt_cantidadDisponible.setText(stock);
                FrmActualizarProducto.txt_IDP.setText(String.valueOf(ID1));
                this.setVisible(false);
                con.close();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No contiene un producto");
                
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto","Sistema",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void irADAlmacen(){
        this.setVisible(false);
        FrmDetallesAlmacen almacen = new FrmDetallesAlmacen();
        almacen.setVisible(true);
    }
    
    public void mostrarDatos(){
        
        String[] titulos={"ID","Nombre_Producto","Marca","Categoría","Precio","Cantidad_Disponible"};
        String[] registros = new String[6];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        
        String SQL = "select * from productos";
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            
            
            
            while (rs.next()) {                
                
                registros[0]=rs.getString("idProducto");
                registros[1]=rs.getString("NombreProducto");
                registros[2]=rs.getString("MarcaProducto");
                registros[3]=rs.getString("CategoriaProducto");
                registros[4]=rs.getString("PrecioProducto");
                registros[5]=rs.getString("StockProducto");
                
                modelo.addRow(registros);
                
            }
            
            tblProductos.setModel(modelo);
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Error al cargar los datos"+e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDatosProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDatosProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_detallesAlmacen;
    private javax.swing.JButton btn_irAGestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
