/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datos;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import login.login;
import conex.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrmDatosRegistro extends javax.swing.JFrame {

    
    conexion cc = new conexion();
    Connection con = cc.conexion();
    /**
     * Creates new form frmDatos
     */
    public FrmDatosRegistro() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnIrAGestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Clientes registrados");

        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCerrar.setText("Cerrar seccion");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnIrAGestion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnIrAGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/íconos/back_previous_arrow_left_19320.png"))); // NOI18N
        btnIrAGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrAGestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(242, 242, 242)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnIrAGestion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addGap(43, 43, 43)
                        .addComponent(btnEliminar)
                        .addGap(40, 40, 40)
                        .addComponent(btnCerrar)
                        .addGap(39, 39, 39)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIrAGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCerrar)
                        .addComponent(btnEliminar)
                        .addComponent(btnActualizar)))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarRegistros();
        mostrarDatos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        irALogin();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        enviarDatosVentana();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnIrAGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrAGestionActionPerformed
        irAGestion();
    }//GEN-LAST:event_btnIrAGestionActionPerformed
    
    public void enviarDatosVentana(){
        if (tblClientes.getSelectedRow()>=0) {
        FrmDetallesUsuario abrir = new FrmDetallesUsuario();
        abrir.setVisible(true);
            try {
                DefaultTableModel tm = (DefaultTableModel)tblClientes.getModel();
                
                int ID1 = Integer.parseInt(String.valueOf(tm.getValueAt(tblClientes.getSelectedRow(),0)));
                String nombreUsuario = String.valueOf(tm.getValueAt(tblClientes.getSelectedRow(), 1));
                String nombre = String.valueOf(tm.getValueAt(tblClientes.getSelectedRow(), 2));
                String apellido = String.valueOf(tm.getValueAt(tblClientes.getSelectedRow(), 3));
                String telefono = String.valueOf(tm.getValueAt(tblClientes.getSelectedRow(), 4));
                String email = String.valueOf(tm.getValueAt(tblClientes.getSelectedRow(), 5));
                
                FrmDetallesUsuario.txt_nombre.setText(nombre);
                FrmDetallesUsuario.txt_usuario.setText(nombreUsuario);
                FrmDetallesUsuario.txt_telefono.setText(telefono);
                FrmDetallesUsuario.txt_apellido.setText(apellido);
                FrmDetallesUsuario.txt_email.setText(email);
                FrmDetallesUsuario.txt_ID.setText(String.valueOf(ID1));
                this.setVisible(false);
                con.close();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No contiene un producto");
                
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto","Sistema",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void irAGestion(){
        this.setVisible(false);
        Frmgestion gestion = new Frmgestion();
        gestion.setVisible(true);
    
    }
    
    public void irALogin(){
        this.setVisible(false);
        login lo = new login();
        lo.setVisible(true);
    
    }
    
   
    
    public void eliminarRegistros(){
        int filaSeleccionada = tblClientes.getSelectedRow();
        
        try {
            String SQL = "delete from usuarios where idusuarios="+tblClientes.getValueAt(filaSeleccionada,0);
            
            Statement st = con.createStatement();
            
            int n = st.executeUpdate(SQL);
            
            if (n>=0) {
                
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Eliminar registro, debe seleccionar un campo"+e.getMessage());
        }
        
    }
    
    
    
    public void mostrarDatos(){
        
        String[] titulos={"ID","Nombre_Usuario","Nombre","Apellido","Numero_Telefono","Email"};
        String[] registros = new String[6];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        
        String SQL = "select * from usuarios";
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            
            
            
            while (rs.next()) {                
                
                registros[0]=rs.getString("idusuarios");
                registros[1]=rs.getString("NombreUsuario");
                registros[2]=rs.getString("Nombre");
                registros[3]=rs.getString("Apellido");
                registros[4]=rs.getString("Telefono");
                registros[5]=rs.getString("Email");
                
                modelo.addRow(registros);
                
            }
            
            tblClientes.setModel(modelo);
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Error al cargar los datos"+e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDatosRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDatosRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDatosRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDatosRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDatosRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIrAGestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
