/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registro;

import clientes.SqlUsuarios;
import clientes.Usuarios;
import clientes.hash;
import com.mysql.jdbc.JDBC4PreparedStatement;
import login.login;
import conex.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class registro extends javax.swing.JFrame {

    conexion cc = new conexion();
    Connection con = cc.conexion();

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
        setLocationRelativeTo(null);
        TextPrompt nombreUsuario = new TextPrompt("Nombre de Usuario", txtnombre_usuario);
        TextPrompt nombre = new TextPrompt("Nombre", txtNombre);
        TextPrompt apellido = new TextPrompt("Apellido", txtApellido);
        TextPrompt numeroTelefono = new TextPrompt("Numero de Telefono", txtNumeroTelefono);
        TextPrompt correoElectronico = new TextPrompt("Correo Electronico", txtCorreoE);
        TextPrompt contraseña = new TextPrompt("Contraseña", txtContraseña);
        TextPrompt confirmarContraseña = new TextPrompt("Confirmar Contraseña", txtConfirmarContraseña);
        lbl_nU.setVisible(false);
        lbl_n.setVisible(false);
        lbl_a.setVisible(false);
        lbl_t.setVisible(false);
        lbl_e.setVisible(false);
        lbl_c.setVisible(false);
        lbl_cC.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre_usuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreoE = new javax.swing.JTextField();
        txtNumeroTelefono = new javax.swing.JTextField();
        btnirALogin = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        lbl_nU = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        lbl_n = new javax.swing.JLabel();
        lbl_e = new javax.swing.JLabel();
        lbl_c = new javax.swing.JLabel();
        lbl_t = new javax.swing.JLabel();
        lbl_cC = new javax.swing.JLabel();

        jLabel7.setText("CAMPO OBLIGATORIO (*)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        txtnombre_usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnombre_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnombre_usuarioFocusLost(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoFocusLost(evt);
            }
        });

        txtCorreoE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCorreoE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoEFocusLost(evt);
            }
        });

        txtNumeroTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNumeroTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroTelefonoFocusLost(evt);
            }
        });

        btnirALogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnirALogin.setText("Registrar");
        btnirALogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnirALoginActionPerformed(evt);
            }
        });

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/íconos/Go-back_36760.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtContraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseñaFocusLost(evt);
            }
        });

        txtConfirmarContraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtConfirmarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmarContraseñaFocusLost(evt);
            }
        });

        lbl_nU.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_nU.setForeground(new java.awt.Color(255, 51, 51));
        lbl_nU.setText("CAMPO OBLIGATORIO (*)");

        lbl_a.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_a.setForeground(new java.awt.Color(255, 51, 51));
        lbl_a.setText("CAMPO OBLIGATORIO (*)");

        lbl_n.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_n.setForeground(new java.awt.Color(255, 51, 51));
        lbl_n.setText("CAMPO OBLIGATORIO (*)");

        lbl_e.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_e.setForeground(new java.awt.Color(255, 51, 51));
        lbl_e.setText("CAMPO OBLIGATORIO (*)");

        lbl_c.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_c.setForeground(new java.awt.Color(255, 51, 51));
        lbl_c.setText("CAMPO OBLIGATORIO (*)");

        lbl_t.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_t.setForeground(new java.awt.Color(255, 51, 51));
        lbl_t.setText("CAMPO OBLIGATORIO (*)");

        lbl_cC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_cC.setForeground(new java.awt.Color(255, 51, 51));
        lbl_cC.setText("CAMPO OBLIGATORIO (*)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_t)
                    .addComponent(lbl_a)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(txtnombre_usuario)
                    .addComponent(lbl_nU)
                    .addComponent(lbl_n)
                    .addComponent(txtApellido)
                    .addComponent(txtNumeroTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_cC)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(txtConfirmarContraseña)
                        .addComponent(lbl_e)
                        .addComponent(txtCorreoE))
                    .addComponent(lbl_c))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(btnirALogin)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nU)
                    .addComponent(lbl_cC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnombre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtContraseña))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_n, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_e))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_a)
                    .addComponent(lbl_c))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_t)
                .addGap(18, 18, 18)
                .addComponent(txtNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnirALogin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnirALoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnirALoginActionPerformed
       

        SqlUsuarios modSql = new SqlUsuarios();
        Usuarios mod = new Usuarios();

        String pass = new String(txtContraseña.getPassword());
        String passCon = new String(txtConfirmarContraseña.getPassword());

        if (txtnombre_usuario.getText().trim().equals("") || pass.trim().equals("") || passCon.trim().equals("") || txtNombre.getText().trim().equals("") || txtApellido.getText().trim().equals("") || txtNumeroTelefono.getText().trim().equals("") || txtCorreoE.getText().trim().equals("")) {

            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los campos","Error",JOptionPane.WARNING_MESSAGE);
            lbl_nU.setVisible(true);
            lbl_n.setVisible(true);
            lbl_a.setVisible(true);
            lbl_t.setVisible(true);
            lbl_e.setVisible(true);
            lbl_c.setVisible(true);
            lbl_cC.setVisible(true);
        } else {

            if (pass.equals(passCon)) {

                if (modSql.existeUsuario(txtnombre_usuario.getText()) == 0) {

                    if (modSql.esEmail(txtCorreoE.getText())) {

                        String nuevoPass = hash.sha1(pass);

                        mod.setUsuario(txtnombre_usuario.getText());
                        mod.setNombre(txtNombre.getText());
                        mod.setApellido(txtApellido.getText());
                        mod.setTelefono(txtNumeroTelefono.getText());
                        mod.setEmail(txtCorreoE.getText());
                        mod.setContraseña(nuevoPass);

                        if (modSql.registrar(mod)) {

                            JOptionPane.showMessageDialog(null, "Registro guardado","Aviso",JOptionPane.INFORMATION_MESSAGE);
                            lbl_nU.setVisible(false);
                            lbl_n.setVisible(false);
                            lbl_a.setVisible(false);
                            lbl_t.setVisible(false);
                            lbl_e.setVisible(false);
                            lbl_c.setVisible(false);
                            lbl_cC.setVisible(false);
                            irAlogin();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al guardar");

                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El correo electronico no es valido");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }
        }


    }//GEN-LAST:event_btnirALoginActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        irAlogin();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtnombre_usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombre_usuarioFocusLost
        if (txtnombre_usuario.getText().trim().isEmpty()) {
            
            lbl_nU.setVisible(true);
        }else{
           lbl_nU.setVisible(false); 
        }
    }//GEN-LAST:event_txtnombre_usuarioFocusLost

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if (txtNombre.getText().trim().isEmpty()) {
            
            lbl_n.setVisible(true);
        }else{
            lbl_n.setVisible(false);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusLost
        if (txtApellido.getText().trim().isEmpty()) {
            
            lbl_a.setVisible(true);
        }
        else{
            lbl_a.setVisible(false);
        }
    }//GEN-LAST:event_txtApellidoFocusLost

    private void txtNumeroTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroTelefonoFocusLost
        if (txtNumeroTelefono.getText().trim().isEmpty()) {
            
            lbl_t.setVisible(true);
        }else{
            lbl_t.setVisible(false);
        }
    }//GEN-LAST:event_txtNumeroTelefonoFocusLost

    private void txtCorreoEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoEFocusLost
        if (txtCorreoE.getText().trim().isEmpty()) {
            
            lbl_e.setVisible(true);
        }else{
            lbl_e.setVisible(false);
        }
        
    }//GEN-LAST:event_txtCorreoEFocusLost

    private void txtContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaFocusLost
        if (txtContraseña.getText().trim().isEmpty()) {
            
            lbl_c.setVisible(true);
        }else{
            lbl_c.setVisible(false);
        }
    }//GEN-LAST:event_txtContraseñaFocusLost

    private void txtConfirmarContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmarContraseñaFocusLost
        if (txtConfirmarContraseña.getText().trim().isEmpty()) {
            
            lbl_cC.setVisible(true);
        }else{
            lbl_cC.setVisible(false);
        }
    }//GEN-LAST:event_txtConfirmarContraseñaFocusLost

    
    public void irAlogin() {
        this.setVisible(false);
        login l = new login();
        l.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnirALogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_c;
    private javax.swing.JLabel lbl_cC;
    private javax.swing.JLabel lbl_e;
    private javax.swing.JLabel lbl_n;
    private javax.swing.JLabel lbl_nU;
    private javax.swing.JLabel lbl_t;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtConfirmarContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreoE;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroTelefono;
    private javax.swing.JTextField txtnombre_usuario;
    // End of variables declaration//GEN-END:variables
}
